# Generated by Django 3.2.9 on 2021-11-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_raiting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(default='admin', max_length=50, verbose_name='имя автора'),
        ),
    ]
