# Generated by Django 3.2.9 on 2021-11-28 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_alter_raiting_user_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='raite',
        ),
        migrations.AlterField(
            model_name='raiting',
            name='user_raiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
