# Generated by Django 3.2.9 on 2021-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='review_title', max_length=250, unique_for_date='publish'),
        ),
    ]
