# Generated by Django 3.2.9 on 2021-11-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20211129_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categoru', models.CharField(max_length=100, verbose_name='Имя категории')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(verbose_name='текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=200, verbose_name='название отзыва'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image_push',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='review',
            name='caregoru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.categoru'),
        ),
    ]
