# Generated by Django 3.2.9 on 2021-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20211129_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rait',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, max_length=1),
        ),
    ]
