# Generated by Django 3.2.9 on 2021-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_review_rait'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiting',
            name='star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
        ),
    ]
