# Generated by Django 3.2.9 on 2021-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20211201_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='star',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
