# Generated by Django 3.2.9 on 2021-12-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_alter_raiting_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='prev_text',
            field=models.CharField(default='', max_length=400, verbose_name='Превью текст'),
        ),
    ]
