# Generated by Django 3.2.9 on 2021-12-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_review_prev_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='caregoru',
            new_name='categoru',
        ),
    ]
