# Generated by Django 3.2.9 on 2021-12-01 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_rename_caregoru_review_categoru'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время рубликации'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
