# Generated by Django 3.2.9 on 2021-12-01 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20211201_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
